### PR TITLE
Fix country bug

### LINKED ISSUE #18: No results when I specify more than one country
```
Arch Linux
arch-reflector 1.1.1
```

```
$ reflector --protocol https --country Spain --latest 5
################################################################################
################# Arch Linux mirrorlist generated by Reflector #################
################################################################################

# With:       reflector --protocol https --country Spain --latest 5
# When:       2026-02-15T10:16:32.359912443Z
# From:       https://archlinux.org/mirrors/status/json/
# Retrieved:  2026-02-15T10:16:09.233031659Z
# Last Check: 2026-02-15T09:10:44.964Z

Server = https://ftp.rediris.es/mirror/archlinux/$repo/os/$arch
Server = https://mirror.es.cdn-perfprod.com/archlinux/$repo/os/$arch
Server = https://es.mirrors.cicku.me/archlinux/$repo/os/$arch
Server = https://nox.panibrez.com/archlinux/$repo/os/$arch
Server = https://mirror.raiolanetworks.com/archlinux/$repo/os/$arch

```
```
$ reflector --protocol https --country France --latest 5
################################################################################
################# Arch Linux mirrorlist generated by Reflector #################
################################################################################

# With:       reflector --protocol https --country France --latest 5
# When:       2026-02-15T10:16:15.311760341Z
# From:       https://archlinux.org/mirrors/status/json/
# Retrieved:  2026-02-15T10:16:09.233031659Z
# Last Check: 2026-02-15T09:10:44.964Z

Server = https://mirrors.gandi.net/archlinux/$repo/os/$arch
Server = https://mirror.its-tps.fr/archlinux/$repo/os/$arch
Server = https://archlinux.mirrors.ovh.net/archlinux/$repo/os/$arch
Server = https://mirror.wormhole.eu/archlinux/$repo/os/$arch
Server = https://mirrors.eric.ovh/arch/$repo/os/$arch

```
```
$ reflector --protocol https --country Spain,France --latest 5
################################################################################
################# Arch Linux mirrorlist generated by Reflector #################
################################################################################

# With:       reflector --protocol https --country Spain,France --latest 5
# When:       2026-02-15T10:17:18.297901589Z
# From:       https://archlinux.org/mirrors/status/json/
# Retrieved:  2026-02-15T10:16:09.233031659Z
# Last Check: 2026-02-15T09:10:44.964Z
```

With **original** `reflector`:
```
$ reflector --protocol https --country Spain,France --latest 5
################################################################################
################# Arch Linux mirrorlist generated by Reflector #################
################################################################################

# With:       reflector --protocol https --country Spain,France --latest 5
# When:       2026-02-15 10:23:43 UTC
# From:       https://archlinux.org/mirrors/status/json/
# Retrieved:  2026-02-15 10:23:43 UTC
# Last Check: 2026-02-15 10:19:21 UTC

Server = https://mirror.theo546.fr/archlinux/$repo/os/$arch
Server = https://mirror.trap.moe/archlinux/$repo/os/$arch
Server = https://mirror.cyberbits.eu/archlinux/$repo/os/$arch
Server = https://archlinux.mailtunnel.eu/$repo/os/$arch
Server = https://nox.panibrez.com/archlinux/$repo/os/$arch
```

### PR DESCRIPTION
**Pull request by dpvpro**
Fix #18

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -1,3 +1,4 @@
 /target
 .env
 tmp
+info/
```
Comment (james7132) [inline .gitignore]: Where is this coming from?
```suggestion
```

File: crates/arch-reflector/src/main.rs [hunk 2]
```diff
@@ -552,11 +552,14 @@ fn filter_status(filters: &Filters, status: &mut Status) {
...
 
-        if !filters.country.is_empty()
-            && !filters.country.contains(&mirror.country)
-            && !filters.country.contains(&mirror.country_code)
-        {
-            return false;
+        if !filters.country.is_empty() {
+            let country_matches = filters.country.iter().any(|c| {
+                let trimmed = c.trim();
+                trimmed == "*" || trimmed == mirror.country || trimmed == mirror.country_code
```
Comment (james7132) [inline crates/arch-reflector/src/main.rs]: Checking the original Python source code, it seems like it was a case insensitive match:

```python
        # Filter by countries.
        countries = self.countries
        if countries and '*' not in countries:
            mirrors = (
                m for m in mirrors
                if m['country'].upper() in countries or m['country_code'].upper() in countries
            )
```

Might as well fix this while we're at it.

File: .gitignore (hunk 1 above)
Comment (dpvpro) [reply .gitignore]: I delete commit

Comment (dpvpro) [reply .gitignore]: i delete commit

File: crates/arch-mirrors-rs/Cargo.toml [hunk 3]
```diff
@@ -1,7 +1,7 @@
 [package]
 name = "arch-mirrors-rs"
 description = "Parse the Arch Linux mirror status."
-version = "1.1.1"
+version = "1.1.2"
```
Comment (james7132) [inline crates/arch-mirrors-rs/Cargo.toml]: Please separate out the version bump. I'll do this separately, since I'll also update the AUR packages.

File: mise.toml [hunk 4]
```diff
@@ -0,0 +1,2 @@
+[tools]
+rust = "1.91.0"
```
Comment (james7132) [inline mise.toml]: Please omit this file. That isn't the MSRV either.

**Review by james7132 — CHANGES_REQUESTED** [review]
Please do rebase on `main`. I merged in a number of Dependabot updates.

File: mise.toml (hunk 4 above)
Comment (dpvpro) [reply mise.toml]: Which version rust should it be used for devlopment?

Comment (james7132) [reply mise.toml]: It says on the README: currently 1.85.

If we must use a toolchain lock to enforce this, using a `rust-toolchain.toml` is my preference, but that will require some CI changes to get it to work appropriately, and that should probably be done in a separate PR.

File: crates/arch-reflector/src/main.rs [hunk 5]
```diff
@@ -552,11 +552,19 @@ fn filter_status(filters: &Filters, status: &mut Status) {
...
-            return false;
+        if !filters.country.is_empty() {
+            let country_matches = filters.country.iter().any(|c| {
+                let trimmed = c.trim();
+                if trimmed == "*" {
+                    return true;
+                }
+                let trimmed_upper = trimmed.to_uppercase();
+                trimmed_upper == mirror.country.to_uppercase()
+                    || trimmed_upper == mirror.country_code.to_uppercase()
```
Comment (james7132) [inline crates/arch-reflector/src/main.rs]:
```suggestion
                // All country names are in English and all country codes are in ASCII.
                trimmed.eq_ignore_ascii_case(mirror.country.as_str())
                    || trimmed..eq_ignore_ascii_case(mirror.country_code.as_str())
```
This should be equivalent for this particular use case, without the extra allocations and copying, since the country name are in English and all country codes are in ASCII.

**Review by james7132 — DISMISSED** [review]

File: mise.toml (hunk 4 above)
Comment (dpvpro) [reply mise.toml]: Ok, i got it. No need to change CI.

File: crates/arch-reflector/src/main.rs (hunk 5 above)
Comment (dpvpro) [reply crates/arch-reflector/src/main.rs]: I can't build with you suggestion. Have you checked your changes? And i have some rust version's error at building. I use rust 1.85.1.

```
~/C/r/reflector-rs (main)> cargo install --path crates/arch-reflector
  Installing arch-reflector v1.1.1 (/home/dp/Code/rust/reflector-rs/crates/arch-reflector)
    Updating crates.io index
     Locking 204 packages to latest compatible versions
      Adding wasip2 v1.0.2+wasi-0.2.9 (requires Rust 1.87.0)
      Adding wasip3 v0.4.0+wasi-0.3.0-rc-2026-01-06 (requires Rust 1.87.0)
      Adding wit-bindgen v0.51.0 (requires Rust 1.87.0)
      Adding wit-bindgen-core v0.51.0 (requires Rust 1.87.0)
      Adding wit-bindgen-rust v0.51.0 (requires Rust 1.87.0)
   Compiling proc-macro2 v1.0.106
```

```
Compiling arch-reflector v1.1.1 (/home/dp/Code/rust/reflector-rs/crates/arch-reflector)
error[E0425]: cannot find function `eq_ignore_ascii_case` in this scope --> crates/arch-reflector/src/main.rs:563:33
    |
563 |                     || trimmed..eq_ignore_ascii_case(mirror.country_code.as_str())
    |                                 ^^^^^^^^^^^^^^^^^^^^ not found in this scope
    |
help: you might have meant to write `.` instead of `..`
    |
563 -                     || trimmed..eq_ignore_ascii_case(mirror.country_code.as_str())
563 +                     || trimmed.eq_ignore_ascii_case(mirror.country_code.as_str())
    |

error[E0308]: mismatched types
   --> crates/arch-reflector/src/main.rs:563:24
    |
562 |                 trimmed.eq_ignore_ascii_case(mirror.country.as_str())
    |                 ----------------------------------------------------- expected because this is `bool`
563 |                     || trimmed..eq_ignore_ascii_case(mirror.country_code.as_str())
    |                        ^^^^^^^ expected `bool`, found `&str`

error[E0308]: mismatched types
   --> crates/arch-reflector/src/main.rs:562:17
    |
562 | /                 trimmed.eq_ignore_ascii_case(mirror.country.as_str())
563 | |                     || trimmed..eq_ignore_ascii_case(mirror.country_code.as_str())
    | |__________________________________________________________________________________^ expected `bool`, found `Range<bool>`
    |
    = note: expected type `bool`
             found struct `std::ops::Range<bool>`
note: return type inferred to be `bool` here
   --> crates/arch-reflector/src/main.rs:559:28
    |
559 |                     return true;
    |                            ^^^^

Some errors have detailed explanations: E0308, E0425.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `arch-reflector` (bin "reflector") due to 3 previous errors
error: failed to compile `arch-reflector v1.1.1 (/home/dp/Code/rust/reflector-rs/crates/arch-reflector)`, intermediate artifacts can be found at `/home/dp/Code/rust/reflector-rs/target`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

```

Comment (dpvpro) [reply crates/arch-reflector/src/main.rs]: I fix second error. There was extra dot in your code.

Comment (dpvpro) [reply crates/arch-reflector/src/main.rs]: But what about version warnings or errors?
